from __future__ import annotations


DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8787
PORT_SEARCH_ATTEMPTS = 100
DEFAULT_PROXY_BASE = "/v1"
DEFAULT_SERVICE_TIER = "priority"
DEFAULT_SERVICE_TIER_POLICY = "auto"
INTERNAL_UPSTREAM_API_KEY_ENV = "CODEX_FAST_PROXY_UPSTREAM_API_KEY"
